--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DavyCraft648/MentionSound
build-by-default: true
branches:
- main
projects:
  MentionSound:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
...
